# Generated by Django 4.2 on 2024-02-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("authorname", models.CharField(max_length=60)),
                ("img", models.ImageField(blank=True, null=True, upload_to="images/")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
